# Generated by Django 4.1.5 on 2023-01-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.TextField(default='question loading error')),
                ('answers', models.IntegerField(null=True)),
                ('option1', models.TextField(blank=True)),
                ('option2', models.TextField(blank=True)),
                ('option3', models.TextField(blank=True)),
                ('option4', models.TextField(blank=True)),
            ],
        ),
    ]
