# Generated by Django 4.1.5 on 2023-01-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_quiz_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
