# Generated by Django 4.1.5 on 2023-01-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_quiz_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
